language: php

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: hhvm


  allow_failures:
  - php: hhvm

services:
  - mysql

env:
  - PHPUNIT_DB_CONNECTION=testing_mysql

cache:
  directories:
    - vendor
    - $HOME/.cache/composer

before_install:
  # Disable xdebug (hhvm doesn't support xdebug)
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - mysql -e 'CREATE DATABASE IF NOT EXISTS phpunit_librenms;'

install:
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - git reset --hard HEAD
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n -p --colors --extensions=php --standard=PSR2 --ignore=/vendor,/storage,/database,/public,/bootstrap/cache,/_ide_helper.php ./
